import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, RefreshControl, StyleSheet, TextInput as NativeTextInput, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Badge, Button, Card, Text } from 'react-native-paper';
import { Screen } from '../components/Screen';
import { ErrorNotice } from '../components/ErrorNotice';
import { apiError, mobileApi } from '../services/api';
import type { Food } from '../types';

export function MenuScreen({ navigation }: { navigation: { navigate: (name: string) => void } }) {
  const [foods, setFoods] = useState<Food[]>([]); const [cartCount, setCartCount] = useState(0); const [error, setError] = useState<string>(); const [refreshing, setRefreshing] = useState(false); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All');
  const load = async () => { setRefreshing(true); try { setError(undefined); const [menu, cart] = await Promise.all([mobileApi.foods(), mobileApi.cart()]); setFoods(menu); setCartCount(cart.reduce((total, item) => total + Number(item.quantity), 0)); } catch (e) { setError(apiError(e).message); } finally { setRefreshing(false); } };
  useFocusEffect(useCallback(() => { load(); }, []));
  const categories = useMemo(() => ['All', ...Array.from(new Set(foods.map(food => food.category).filter(Boolean)))], [foods]);
  const visible = foods.filter(food => (category === 'All' || food.category === category) && `${food.title} ${food.detail ?? ''}`.toLowerCase().includes(query.toLowerCase()));
  const add = async (food: Food) => { try { await mobileApi.addToCart(food.id); setCartCount(value => value + 1); } catch (e) { setError(apiError(e).message); } };
  return <Screen refreshControl={<RefreshControl refreshing={refreshing} onRefresh={load} tintColor="#8d197f" />}><View style={styles.header}><View style={styles.brand}><Text style={styles.brandText}>MC</Text></View><Text style={styles.menuTitle}>Menu</Text><Pressable accessibilityLabel="Refresh menu" onPress={load} style={styles.headerButton}><Text style={styles.refresh}>↻</Text></Pressable><Pressable accessibilityLabel="Open cart" onPress={() => navigation.navigate('Cart')} style={styles.cartButton}><Text style={styles.cartIcon}>🛒</Text>{cartCount > 0 && <Badge style={styles.badge}>{cartCount}</Badge>}</Pressable></View><View style={styles.content}><Text style={styles.heading}>What are you craving?</Text><Text style={styles.subtitle}>Choose a category, then add your favorites to cart.</Text><View style={styles.chips}>{categories.map(item => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item === 'All' ? 'All menu' : item}</Text></Pressable>)}</View><View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><NativeTextInput value={query} onChangeText={setQuery} placeholder="Search the menu" placeholderTextColor="#9ba0a8" style={styles.searchInput} /></View><ErrorNotice message={error} />{visible.map(food => <FoodCard key={food.id} food={food} adding={false} onAdd={() => add(food)} />)}{!refreshing && !visible.length && <Text style={styles.empty}>No menu items found.</Text>}</View></Screen>;
}
function FoodCard({ food, onAdd }: { food: Food; adding: boolean; onAdd: () => void }) {
  const [loading, setLoading] = useState(Boolean(food.image_url)); const [failed, setFailed] = useState(!food.image_url);
  return <Card style={styles.card}><Card.Content style={styles.cardContent}>{failed ? <View style={styles.placeholder}><Text style={styles.placeholderText}>MC</Text></View> : <View style={styles.imageFrame}>{loading && <ActivityIndicator style={styles.loader} color="#8d197f" />}{food.image_url && <Image source={{ uri: food.image_url }} style={styles.image} resizeMode="cover" onLoadEnd={() => setLoading(false)} onError={() => { setLoading(false); setFailed(true); }} />}</View>}<View style={styles.details}><Text style={styles.foodName}>{food.title}</Text><Text style={styles.price}>₱{food.price.toFixed(2)}</Text><Text style={[styles.stock, food.stock < 1 && styles.outOfStock]}>{food.stock > 0 ? `${food.stock} available` : 'Out of stock'}</Text><Button mode="contained" buttonColor="#8d197f" style={styles.addButton} labelStyle={styles.addLabel} disabled={food.stock < 1} onPress={onAdd}>Add to cart</Button></View></Card.Content></Card>;
}
const styles = StyleSheet.create({ header: { alignItems: 'center', backgroundColor: '#fff', borderBottomColor: '#e5e5e5', borderBottomWidth: 1, flexDirection: 'row', gap: 12, padding: 18 }, brand: { alignItems: 'center', backgroundColor: '#e70db5', borderRadius: 21, height: 72, justifyContent: 'center', width: 72 }, brandText: { color: '#fff', fontSize: 24, fontWeight: '900' }, menuTitle: { color: '#1f2329', flex: 1, fontSize: 35, fontWeight: '800' }, headerButton: { padding: 5 }, refresh: { color: '#8d197f', fontSize: 42, lineHeight: 42 }, cartButton: { alignItems: 'center', backgroundColor: '#fae7f5', borderRadius: 34, height: 64, justifyContent: 'center', width: 64 }, cartIcon: { fontSize: 30 }, badge: { backgroundColor: '#8d197f', color: '#fff', position: 'absolute', right: -2, top: -6 }, content: { gap: 16, padding: 22 }, heading: { color: '#20242a', fontSize: 38, fontWeight: '900', letterSpacing: -1 }, subtitle: { color: '#6d737d', fontSize: 18, lineHeight: 25, marginTop: -9 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, chip: { backgroundColor: '#fff', borderRadius: 28, paddingHorizontal: 23, paddingVertical: 14 }, chipActive: { backgroundColor: '#8d197f' }, chipText: { color: '#8d197f', fontSize: 16, fontWeight: '800' }, chipTextActive: { color: '#fff' }, search: { alignItems: 'center', backgroundColor: '#fff', borderColor: '#e3e3e5', borderRadius: 20, borderWidth: 1, flexDirection: 'row', height: 74, paddingHorizontal: 20 }, searchIcon: { color: '#82868d', fontSize: 37, marginRight: 12 }, searchInput: { color: '#262a30', flex: 1, fontSize: 20, height: '100%' }, card: { backgroundColor: '#fff', borderColor: '#e3e3e5', borderRadius: 25, borderWidth: 1, elevation: 2, marginTop: 4 }, cardContent: { flexDirection: 'row', gap: 18, padding: 18 }, imageFrame: { alignItems: 'center', backgroundColor: '#f9e4f5', borderRadius: 20, height: 145, justifyContent: 'center', overflow: 'hidden', width: 118 }, image: { height: '100%', width: '100%' }, loader: { position: 'absolute' }, placeholder: { alignItems: 'center', backgroundColor: '#f9e4f5', borderRadius: 20, height: 145, justifyContent: 'center', width: 118 }, placeholderText: { color: '#8d197f', fontSize: 27, fontWeight: '900' }, details: { flex: 1, gap: 5 }, foodName: { color: '#1f2329', fontSize: 22, fontWeight: '900', lineHeight: 27 }, price: { color: '#8d197f', fontSize: 22, fontWeight: '900' }, stock: { color: '#158456', fontSize: 17, fontWeight: '600' }, outOfStock: { color: '#b04b4b' }, addButton: { borderRadius: 26, marginTop: 'auto', minHeight: 46, justifyContent: 'center' }, addLabel: { fontSize: 16, fontWeight: '800' }, empty: { color: '#6d737d', fontSize: 17, textAlign: 'center' } });
